///////////////////////////////////
/*

Do not edit this file! Contains class names for all weapons.

Arrays:

_BAF_Rifles
_BAF_Rifle_Ammo
_BAF_MGs
_BAF_MG_Ammo
_BAF_Snipers
_BAF_Sniper_Ammo
_BAF_Launchers
_BAF_Launcher_Ammo

_US_Rifles
_US_Rifle_Ammo
_US_MGs
_US_MG_Ammo
_US_Snipers
_US_Sniper_Ammo
_US_Launchers
_US_Launcher_Ammo

_EU_Rifles
_EU_Rifle_Ammo
_EU_MGs
_EU_MG_Ammo
_EU_Snipers
_EU_Sniper_Ammo
_EU_Launchers
_EU_Launcher_Ammo

_PMC_Rifles
_PMC_Rifle_Ammo
_PMC_MGs
_PMC_MG_Ammo

_itemsWeapon
_itemsAmmo

*/
///////////////////////////////////

_BAF_Rifles = [
"BAF_L85A2_RIS_ACOG", 
"BAF_L85A2_RIS_CWS", 
"BAF_L85A2_RIS_Holo", 
"BAF_L85A2_RIS_SUSAT", 
"BAF_L85A2_UGL_ACOG", 
"BAF_L85A2_UGL_Holo", 
"BAF_L85A2_UGL_SUSAT", 
"BAF_L86A2_ACOG"
];

_BAF_Rifle_Ammo = [
"30Rnd_556x45_Stanag",
"30Rnd_556x45_StanagSD",
"1Rnd_HE_M203",
"1Rnd_Smoke_M203", 
"1Rnd_SmokeGreen_M203", 
"1Rnd_SmokeRed_M203", 
"1Rnd_SmokeYellow_M203", 
"FlareGreen_M203", 
"FlareRed_M203", 
"FlareWhite_M203", 
"FlareYellow_M203"
];

_BAF_MGs = [
"BAF_L110A1_Aim", 
"BAF_L7A2_GPMG"
];

_BAF_MG_Ammo = [
"200Rnd_556x45_L110A1",
"100Rnd_762x51_M240"
];

_BAF_Snipers = [
"BAF_AS50_scoped", 
"BAF_AS50_TWS", 
"BAF_LRR_scoped", 
"BAF_LRR_scoped_W"
];

_BAF_Sniper_Ammo = [
"5Rnd_127x99_as50",
"5Rnd_86x70_L115A1"
];

_BAF_Launchers = [
"BAF_NLAW_Launcher",
"Stinger"
];

_BAF_Launcher_Ammo = [
"NLAW",
"Stinger"
];

_US_Rifles = [
"M14_EP1",
"M16A2",
"M16A2GL",
//"M16A4",
//"M16A4_ACG_GL",
//"M4A1_Aim",
//"M4A1_AIM_SD_camo",
//"M4A1_HWS_GL_camo",
//"M4A1_HWS_GL_SD_Camo",
//"M4A1",
"M4A3_CCO_EP1",
"M4A3_RCO_GL_EP1",
"MP5A5",
"MP5SD",
"SCAR_H_CQC_CCO",
"SCAR_H_CQC_CCO_SD",
"SCAR_H_STD_EGLM_Spect",
"SCAR_H_STD_TWS_SD",
"SCAR_L_CQC",
"SCAR_L_CQC_CCO_SD",
"SCAR_L_CQC_EGLM_Holo",
"SCAR_L_CQC_Holo",
"SCAR_L_STD_EGLM_RCO",
"SCAR_L_STD_EGLM_TWS",
"SCAR_L_STD_HOLO",
"SCAR_L_STD_Mk4CQT"

];

_US_Rifle_Ammo = [
"20Rnd_762x51_DMR",
"100Rnd_556x45_BetaCMag",
"20Rnd_556x45_Stanag",
"30Rnd_9x19_MP5",
"30Rnd_556x45_StanagSD",
"20Rnd_762x51_B_SCAR",
"20Rnd_762x51_SB_SCAR",
"1Rnd_HE_M203", 
"1Rnd_Smoke_M203", 
"1Rnd_SmokeGreen_M203", 
"1Rnd_SmokeRed_M203", 
"1Rnd_SmokeYellow_M203", 
"FlareGreen_M203", 
"FlareRed_M203", 
"FlareWhite_M203", 
"FlareYellow_M203"
];

_US_MGs = [
"m240_scoped_EP1",
"M249_EP1",
"M249_m145_EP1",
"M249_TWS_EP1",
"M60A4_EP1",
"Mk_48_DES_EP1"
];

_US_MG_Ammo = [
"100Rnd_762x51_M240",
"200Rnd_556x45_M249"
];

_US_Snipers = [
"M24_des_EP1",
"M110_NVG_EP1",
"M110_TWS_EP1",
"SCAR_H_LNG_Sniper",
"SCAR_H_LNG_Sniper_SD",
"m107",
"m107_TWS_EP1"
];

_US_Sniper_Ammo = [
"5Rnd_762x51_M24",
"20Rnd_762x51_B_SCAR",
"20Rnd_762x51_SB_SCAR",
"10Rnd_127x99_m107"
];

_US_Launchers = [
"M79_EP1",
"M32_EP1",
"Mk13_EP1",
"Javelin",
"M136",
"M47Launcher_EP1",
"MAAWS",
"Stinger"
];

_US_Launcher_Ammo = [
"1Rnd_HE_M203", 
"1Rnd_Smoke_M203", 
"1Rnd_SmokeGreen_M203", 
"1Rnd_SmokeRed_M203", 
"1Rnd_SmokeYellow_M203", 
"6Rnd_FlareGreen_M203", 
"6Rnd_FlareRed_M203", 
"6Rnd_FlareWhite_M203", 
"6Rnd_FlareYellow_M203", 
"6Rnd_HE_M203", 
"6Rnd_Smoke_M203", 
"6Rnd_SmokeGreen_M203", 
"6Rnd_SmokeRed_M203", 
"6Rnd_SmokeYellow_M203", 
"FlareGreen_M203", 
"FlareRed_M203", 
"FlareWhite_M203", 
"FlareYellow_M203",
"Javelin",
"M136",
"Dragon_EP1",
"MAAWS_HEAT", 
"MAAWS_HEDP",
"Stinger"
];

_EU_Rifles = [
"G36A_camo",
"G36C_camo",
"G36_C_SD_camo",
"G36K_camo",
"Sa58P_EP1",
"Sa58V_EP1",
"Sa58V_CCO_EP1",
"Sa58V_RCO_EP1"
];

_EU_Rifle_Ammo = [
"30Rnd_556x45_G36",
"30Rnd_556x45_G36SD",
"30Rnd_762x39_SA58"
];

_EU_MGs = [
"MG36_camo",
"PK"
];

_EU_MG_Ammo = [
"100Rnd_556x45_BetaCMag",
"100Rnd_762x54_PK"
];

_EU_Snipers = [
"ksvk",
"SVD",
"SVD_des_EP1",
"SVD_NSPU_EP1"
];

_EU_Sniper_Ammo = [
"5Rnd_127x108_KSVK",
"10Rnd_762x54_SVD"
];

_EU_Launchers = [
"M79_EP1",
"Igla",
"M47Launcher_EP1",
"MetisLauncher",
"RPG18"
];

_EU_Launcher_Ammo = [
"Igla",
"Dragon_EP1",
"AT13",
"RPG18",
"1Rnd_HE_M203", 
"1Rnd_Smoke_M203", 
"1Rnd_SmokeGreen_M203", 
"1Rnd_SmokeRed_M203", 
"1Rnd_SmokeYellow_M203",  
"FlareGreen_M203", 
"FlareRed_M203", 
"FlareWhite_M203", 
"FlareYellow_M203"
];

_PMC_Rifles = [
"AA12_PMC",
"m8_carbine",
"m8_carbine_pmc",
"m8_carbineGL",
"m8_compact",
"m8_compact_pmc",
"m8_holo_sd",
"m8_sharpshooter",
"m8_tws",
"m8_sharpshooter"
];

_PMC_Rifle_Ammo = [
"20Rnd_B_AA12_74Slug", 
"20Rnd_B_AA12_HE", 
"20Rnd_B_AA12_Pellets",
"30Rnd_556x45_G36", 
"30Rnd_556x45_G36SD"
];

_PMC_MGs = [
"m8_SAW"
];

_PMC_MG_Ammo = [
"100Rnd_556x45_BetaCMag_airLock"
];

_itemsWeapon = [
"Binocular", 
"Binocular_Vector", 
"NVGoggles", 
"ItemGPS", 
"LaserDesignator"
];

_itemsAmmo = [
"SmokeShell", 
"SmokeShellGreen", 
"SmokeShellRed", 
"SmokeShellYellow", 
"SmokeShellBlue", 
"SmokeShellPurple", 
"SmokeShellOrange", 
"LaserBatteries", 
"HandGrenade_West",
"PipeBomb", 
"Mine", 
"IR_Strobe_Target", 
"IR_Strobe_Marker"
];